R000/urls.py
from django.urls import include, path   
from .import views

app_name='registration'

urlpatterns = [    


    path('', views.college, name="college"),
    path('add/college/', views.add_college, name="add-college"),
    path('insert/college/', views.insert_college, name="insert-college"),

    path('department/<int:college_id>', views.department, name="department"),
    path('add/department/<int:college_id>', views.add_department, name="add-department"),
    path('insert/department/<int:college_id>', views.insert_department, name="insert-department"),

    path('batch/<int:department_id>', views.batch, name="batch"),
    path('add/batch/<int:department_id>', views.add_batch, name="add-batch"),
    path('insert/batch/<int:department_id>', views.insert_batch, name="insert-batch"),

    path('semster/<int:batch_id>', views.semster, name="semster"),
    path('add/semster/<int:batch_id>', views.add_semster, name="add-semster"),
    path('insert/semster/<int:batch_id>', views.insert_semster, name="insert-semster"),

    path('studant/<int:semster_id>', views.studant, name="studant"),

    path('studant/<int:studant_id>/<int:semster_id>', views.edit_studant, name="edit-studant"),
    path('update/<int:studant_id>/studant/<int:semster_id>', views.update_studant, name="update-studant"),

    path('add/studant/<int:semster_id>', views.add_studant, name="add-studant"),
    path('insert/studant/<int:semster_id>', views.insert_studant, name="insert-studant"),

    path('studant/details/<int:studant_id>', views.details, name="details"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls),
    path('', include('R000.urls', namespace='registration')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

R000/models.py
from django.db import models

# Create your models here.

class College(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    address = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.name

class Department(models.Model):
    college = models.ForeignKey(College, on_delete=models.CASCADE, related_name="department_college")
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name
    
class Batch(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="batch_department")
    name = models.CharField(max_length=50, null=True, blank=True)
    def __str__(self):
        return self.name

class Semster(models.Model):
    batch = models.ForeignKey(Batch, null=True, blank=True, on_delete=models.CASCADE, related_name="semster_batch")
    name = models.CharField(max_length=50, null=True, blank=True)
    def __str__(self):
        return self.name

class Nationality(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    def __str__(self):
        return self.name

class Studant(models.Model):
    ACCEPT_TYPE= (
        ('قبول عام', 'قبول عم'),
        ('قبول خاص', 'قبول خاص'),
    )
    GENDER= (
        ('زكر', 'زكر'),
        ('انثى', 'انثى'),
    )  
    TOLL_STATUS= (
        ('تم التسديد', 'تم التسديد '),
        ('لم يتم التسديد', 'لم يتم التسديد'),
    )
    CERTIFICATE_TYPE= (
        ('اكاديمي', 'أكاديمي'),
        ('فني', 'فني'),
        ('تجاري', 'تجاري'),
    )  
    RELIGION= (
        ('مسلم', 'مسلم'),
        ('مسيحي', 'مسيحي'),
        ('غير', 'غير'),
    )  
    BLOODTYPE= (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('O-', 'O-'),
        ('O+', 'O+'),
        ('AB', 'AB'),
    )  
    semster = models.ForeignKey(Semster, null=True, blank=True, on_delete=models.CASCADE, related_name="studant_semster")
    nationality = models.ForeignKey(Nationality, on_delete=models.CASCADE, related_name="studant_nationality", null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    universitiy_number = models.IntegerField(null=True, blank=True)
    accept_type = models.CharField(max_length=190 , null=True, choices=ACCEPT_TYPE)
    accept_at = models.DateTimeField(auto_now_add=True , null=True)
    toll = models.IntegerField(null=True, blank=True)
    toll_status = models.CharField(max_length=190 , null=True, choices=TOLL_STATUS)

    born_at = models.DateTimeField(null=True, blank=True)
    born_in = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=190 , null=True, choices=GENDER)
    public_number = models.IntegerField(null=True, blank=True)
    religion = models.CharField(max_length=190 , null=True, choices=RELIGION)


    address = models.TextField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    email = models.CharField(max_length=190 , null=True)

    school_name = models.CharField(max_length=50, null=True, blank=True)
    blood_type = models.CharField(max_length=190 , null=True, choices=BLOODTYPE)
    certificate_type = models.CharField(max_length=190 , null=True, choices=CERTIFICATE_TYPE)
    accept_degeer = models.IntegerField(null=True, blank=True)
    major = models.CharField(max_length=190 , null=True, blank=True)


    def __str__(self):
        return self.name

R000/forms.py
from django import forms
from .models import Studant, College, Department, Batch, Semster

class CollegeForm(forms.ModelForm):
  class Meta:
    model = College 
    fields = ('name', 'address')
    widgets = { 
          'name': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'required': 'False', 'placeholder':('')}),
          'address': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'required': 'False', 'placeholder':('')}),
    }    
    labels = {
        'name': ('الإسم'),
        'address': ('العنوان'),
      }  

class DepartmentForm(forms.ModelForm):
  class Meta:
    model = Department 
    fields = ('name',)
    widgets = { 
      'name': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'required': 'False', 'placeholder':('')}),
    }    
    labels = {
      'name': ('الإسم')
    }        

class BatchForm(forms.ModelForm):
  class Meta:
    model = Batch 
    fields = ('name',)
    widgets = { 
      'name': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'required': 'False', 'placeholder':('')}),
    }    
    labels = {
      'name': ('الإسم')
    }  

class SemsterForm(forms.ModelForm):
  class Meta:
    model = Semster 
    fields = ('name',)
    widgets = { 
      'name': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'required': 'False', 'placeholder':('')}),
    }    
    labels = {
      'name': ('الإسم')
    }   

class StudantForm(forms.ModelForm):
  class Meta:
    model = Studant
    fields = ('name', 'universitiy_number', 'toll', 'toll_status', 'accept_type',
              'nationality','born_in', 'born_at', 'gender', 'public_number', 'religion',
              'address', 'state', 'city', 'phone_number', 'email',
              'school_name', 'certificate_type', 'accept_degeer','blood_type', 'major',
      )
    widgets = { 
        'name': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'required': 'False', 'placeholder':('')}),
        'universitiy_number': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'blood_type': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'accept_type': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'nationality': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'toll': forms.NumberInput(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'toll_status': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'born_in': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'born_at': forms.DateInput(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'gender': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'public_number': forms.NumberInput(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'religion': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'address': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'state': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'city': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'phone_number': forms.NumberInput(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'email': forms.EmailInput(attrs={'rows':7, 'class':'form-control', 'placeholder':('')}),    
        'school_name': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'certificate_type': forms.Select(attrs={'rows':1,'class':'form-control',  'required': 'False'}),        
        'accept_degeer': forms.NumberInput(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
        'major': forms.Textarea(attrs={'rows':1, 'class':'form-control', 'placeholder':('')}),
    }
    labels = {
        'name': ('الإسم'),
        'universitiy_number': ('الرقم الجامعي'),
        'accept_type': ('نوع القبول'),
        'toll': ('الرسوم'),
        'toll_status': ('الحالة المالية'),
        'nationality': ('الجنسية '),
        'born_in': ('مكان الميلاد'),
        'born_at': ('تاريخ الميلاد'),
        'gender': ('النوع'),
        'public_number': ('الرقم الوطني'),
        'religion': ('الديانة'),
        'address': ('العنوان'),
        'state': ('الولاية'),
        'city': ('المديتة'),
        'phone_number': ('رقم الهاتف'),
        'email': ('البريد الإلكتروني'),
        'school_name': ('اسم المدرسة'),
        'certificate_type': ('نوع الشهادة'),
        'accept_degeer': ('نسبة القبول'),
        'blood_type': (' فصيلة الدم '),
        'major': ('التخصص'),
    }

R000/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import College, Department, Batch, Semster, Studant
from .forms import StudantForm, CollegeForm, DepartmentForm, BatchForm, SemsterForm

from django.contrib.auth.decorators import login_required


# def home(request):
#     context = {}
#     return render(request, 'home/home.html', context)

def about_uni(request):
    context = {}
    return render(request, 'home/about_uni.html', context)

def about_sys(request):
    context = {}
    return render(request, 'home/about_sys.html', context)
    
@login_required
def college(request):
    colleges = College.objects.all()
    context = {'colleges':colleges}
    return render(request, 'college/show.html', context)

def department(request ,college_id):
    college = College.objects.get(id=college_id)
    department = Department.objects.filter(college=college)
    context = {'departments':department, 'college':college}
    return render(request, 'department/show.html', context)

def batch(request ,department_id):
    department = Department.objects.get(id=department_id)
    batch = Batch.objects.filter(department=department)
    context = {'batchs':batch,'department':department}
    return render(request, 'batch/show.html', context)

def semster(request ,batch_id):
    batch = Batch.objects.get(id=batch_id)
    semster = Semster.objects.filter(batch=batch)
    context = {'semsters':semster, 'batch':batch}
    return render(request, 'semster/show.html', context)



def studant(request ,semster_id):
    semster = Semster.objects.get(id=semster_id)
    studant = Studant.objects.filter(semster=semster)
    context = {'studants':studant, 'semster':semster}
    return render(request, 'studant/show.html', context)

def add_studant(request, semster_id):
    semster = Semster.objects.get(id=semster_id)
    context = {
                'semster' : semster,
                'form':StudantForm()
    }
    return render(request, 'studant/add.html', context)

def insert_studant(request, semster_id):
    if request.method == "POST":
        semster = Semster.objects.get(id=semster_id)
        form = StudantForm(request.POST)
        if form.is_valid():  
            Studant.objects.create(
                semster=semster,
				name=form.cleaned_data['name'],
				universitiy_number=form.cleaned_data['universitiy_number'],
				accept_type=form.cleaned_data['accept_type'],
				toll=form.cleaned_data['toll'],
				toll_status=form.cleaned_data['toll_status'],
				born_in=form.cleaned_data['born_in'],
				born_at=form.cleaned_data['born_at'],
				gender=form.cleaned_data['gender'],
				public_number=form.cleaned_data['public_number'],
				nationality=form.cleaned_data['nationality'],
				religion=form.cleaned_data['religion'],
				address=form.cleaned_data['address'],
				state=form.cleaned_data['state'],
				city=form.cleaned_data['city'],
				phone_number=form.cleaned_data['phone_number'],
				email=form.cleaned_data['email'],
				school_name=form.cleaned_data['school_name'],
				certificate_type=form.cleaned_data['certificate_type'],
				accept_degeer=form.cleaned_data['accept_degeer'],
				major=form.cleaned_data['major'],
			)
        else:
            form = StudantForm()
    return redirect("registration:studant", semster_id=semster_id) 

def details(request, studant_id):
    studant = Studant.objects.get(id=studant_id)
    context = {'studant':studant}
    return render(request, 'studant/details.html', context)

def edit_studant(request, semster_id, studant_id):
    semster = Semster.objects.get(pk=semster_id)
    studant = Studant.objects.get(pk=studant_id)
    context = {
                'semster': semster,
                'studant' : studant,
                'form': StudantForm(instance=studant)
    }
    return render(request, 'studant/edit.html', context)

def update_studant(request, semster_id, studant_id):
    if request.method == "POST":
        form = StudantForm(request.POST, instance=Studant.objects.get(pk=studant_id))
        if form.is_valid():  
            form.save()
        else:
            form = StudantForm()
    return redirect("registration:studant", semster_id=semster_id) 


def add_college(request):
    context = {          
        'form':CollegeForm()
    }
    return render(request, 'college/add.html', context)

def insert_college(request):
    if request.method == "POST":
        form = CollegeForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            form = CollegeForm()
    return redirect("registration:college") 

def add_department(request, college_id):
    college = College.objects.get(id=college_id)
    context = {          
        'college':college,
        'form':DepartmentForm(),
    }
    return render(request, 'department/add.html', context)

def insert_department(request, college_id):
    college = College.objects.get(id=college_id)    
    if request.method == "POST":
        form = DepartmentForm(request.POST)
        if form.is_valid():
            Department.objects.create(
                college=college,
                name=form.cleaned_data['name'], 
            )           
        else:
            form = DepartmentForm()
    return redirect("registration:department", college_id=college_id)

def add_batch(request, department_id):
    department = Department.objects.get(id=department_id)
    context = {          
        'department':department,
        'form':BatchForm(),
    }
    return render(request, 'batch/add.html', context)

def insert_batch(request, department_id):
    department = Department.objects.get(id=department_id)  
    if request.method == "POST":
        form = BatchForm(request.POST)
        if form.is_valid():
            Batch.objects.create(
                department=department,
                name=form.cleaned_data['name'], 
            )           
        else:
            form = BatchForm()
    return redirect("registration:batch", department_id=department_id)

def add_semster(request, batch_id):
    batch = Batch.objects.get(id=batch_id)
    context = {          
        'batch':batch,
        'form':SemsterForm(),
    }
    return render(request, 'semster/add.html', context)

def insert_semster(request, batch_id):
    batch = Batch.objects.get(id=batch_id)
    if request.method == "POST":
        form = SemsterForm(request.POST)
        if form.is_valid():
            Semster.objects.create(
                batch=batch,
                name=form.cleaned_data['name'], 
            )           
        else:
            form = SemsterForm()
    return redirect("registration:semster", batch_id=batch_id)

R000/templates/studant/add.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}تسجيل طالب جديد{% endblock title %}
{% block content %}


<section class="add">
    <div class="container">
    <a href="{% url 'registration:studant' semster_id=semster.id %}"><h1><i class="fa fa-fw fa-arrow-circle-right"></i></a></h1>
    <h1>الفصل الدراسي {{semster.name}} /  تسجيل طالب  </h1>
        <form action="{% url 'registration:insert-studant' semster_id=semster.id %}" method="POST" \>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}            
                <tr>
                    <td width="15%"></td>
                    <td width="85%">
                        <button type="submit" class="btn btn-success">تسجيل</button>
                        <a href="{% url 'registration:studant' semster_id=semster.id %}" class="btn btn-default">تراجع</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</section>

{% endblock content %}

R000/templates/studant/details.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}تفاصيل الطالب{% endblock title %}
{% block content %}
<div class="container pt-5">
  <a href="{% url 'registration:studant' semster_id=studant.semster.id %}"><h1><i class="fa fa-fw fa-arrow-circle-right"></i></a></h1>
  <h1>الطالب / {{studant.name}}</h1>
  <div class="box-body">
    <div class="table-responsive">
      <table class="table mb-0">
        <thead class="table-light">
        <tr>
          <th scope="col">رقم الطالب</th>
          <th scope="col">نوع القبول</th>
          <th scope="col">الفصل الدراسي</th>
          <th scope="col">الرسوم</th>
          <th scope="col">الحالة المالية</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">{{studant.id}}</th>
          <td>{{studant.accept_type}}</td>
          <td>{{studant.semster.name}}</td>
          <td>{{studant.toll}} جنيه </td>
          <td>{{studant.toll_status}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="box-body">
    <div class="table-responsive">
      <table class="table mb-0">
        <thead class="table-light">
        <tr>
          <th scope="col">تاريخ الميلا</th>
          <th scope="col">مكان الميلاد</th>
          <th scope="col">النوع</th>
          <th scope="col">الجنسية</th>
          <th scope="col">الديانة</th>
          <th scope="col">الرقم الوطني</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">{{studant.born_at|date:'Y / m / d'}}</th>
          <td>{{studant.born_in}}</td>
          <td>{{studant.gender}}</td>
          <td>{{studant.nationality}}</td>
          <td>{{studant.religion}}</td>
          <td>{{studant.public_number}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="box-body">
    <div class="table-responsive">
      <table class="table mb-0">
        <thead class="table-light">
        <tr>
          <th scope="col">العنوان</th>
          <th scope="col">الولاية</th>
          <th scope="col">المحلية</th>
          <th scope="col">رقم الهاتف</th>
          <th scope="col">البريد الإلكتروني</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">{{studant.address}}</th>
          <td>{{studant.state}}</td>
          <td>{{studant.city}}</td>
          <td>{{studant.phone_number}}</td>
          <td>{{studant.email}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>


  <div class="box-body">
    <div class="table-responsive">
      <table class="table mb-0">
        <thead class="table-light">
        <tr>
          <th scope="col">اسم المدرسم</th>
          <th scope="col">نوع الشهادة</th>
          <th scope="col"> نسبة القبول</th>
          <th scope="col">فصيلة الدم</th>
          <th scope="col"> التخصص</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">{{studant.school_name}}</th>
          <td>{{studant.certificate_type}}</td>
          <td>{{studant.accept_degeer}} %</td>
          <td>{{studant.blood_type}}</td>
          <td>{{studant.major}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>
{% endblock %}

R000/templates/studant/edit.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}تعديل بيانات طالب{% endblock title %}
{% block content %}

<div class="container pt-5">
    <a href="{% url 'registration:studant' semster_id=semster.id %}"><h1><i class="fa fa-fw fa-arrow-circle-right"></i></a></h1>
    <h1>الفصل الدراسي {{semster.name}} /  تعديل بيانات الطالب </h1>
    <section class="add">
        <form action="{% url 'registration:update-studant' semster_id=semster.id studant_id=studant.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}            
                <tr>
                    <td width="15%"></td>
                    <td width="85%">
                        <button type="submit" class="btn btn-success">تحديث</button>
                        <a href="{% url 'registration:studant' semster_id=semster.id %}" class="btn btn-default">تراجع</a>
                    </td>
                </tr>
            </table>
        </form>
    </section>
</div>
{% endblock content %}

R000/templates/studant/show.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}الطلاب{% endblock title %}
{% block content %}

<div class="container pt-5 pb-5">
    {% block auth %}
        {% if 'login' in request.path or 'home' in request.path or 'accounts/logout' in request.path %}
       {% else %}
        <h4>
        <i class="fa fa-sign-out"> &nbsp;&nbsp;</i><a href="{% url 'logout' %}" >تسجيل الخروج</a> 
        </h4>
       {% endif %}
    {% endblock auth %}
<section class="py-md-10">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <div class="me-auto">
                    <div class="d-inline-block align-items-center">
                        <nav>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'registration:college' %}"><h3> الكليات</a></li></h3>
                                <a href="{% url 'registration:department' college_id=semster.batch.department.college.id %}"><h3> / الأقسام</a></h3>
                                <a href="{% url 'registration:batch' department_id=semster.batch.department.id %}"><h3> / الدفع</a></h3>
                                <a href="{% url 'registration:semster' batch_id=semster.batch.id %}"><h3> / الفصول</a></h3>
                                <h3> / الطلاب</h3>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="row">
  <div class="col-lg-12">
    <div class="header-links pb-5">
      <a href="{% url 'registration:add-studant' semster_id=semster.id %}">
        <i class="fa fa-plus-square" aria-hidden="true"></i>&nbsp;تسجيل
      </a>
    </div>
      <div class="table-responsive-md">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr role="row">
                        <th style="width: 5%; text-align: center;">رقم الطالب</th>
                        <th style="width: 20%; text-align: center;">اسم الطالب</th>            
                        <th style="width: 20%; text-align: center;">العمليات</th>
                    </tr>
                </thead>
                    <tbody>
                        {% for studant in studants %}
                            <tr role="row" class="odd">
                                <td style="text-align: center;">{{ forloop.counter }}</td>
                                <td style="text-align: center;">{{ studant.name }}</td>
                                <td style="text-align: center;">
                                      <a href="{% url 'registration:edit-studant' studant_id=studant.id semster_id=semster.id %}">
                                        <i class="fa fa-edit" aria-hidden="true"></i>&nbsp;تعديل
                                    </a>
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="{% url 'registration:details' studant_id=studant.id %}">
                                        <i class="fa fa-eye" aria-hidden="true"></i>&nbsp;التفاصيل 
                                    </a>
                                </td>
                            </tr>
                        {% endfor %} 
                    </tbody>
            </table>
        </div>
    </div>
</div>

</div>

{% endblock %}